sudo: required
language: generic

services:
  - docker

before-install:
  - docker build -t hunainsajid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hunainsajid/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-361547868111"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"