sudo: required
language: generic

services:
  - docker

before-install:
  - docker build -t hunainsajid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hunainsajid/docker-react npm run test
